In [4]:
# A simple robot world can be defined by a 2D array
import numpy as np

world = np.array([
    [0, 0, 0, 1, 0],
    [0, 0, 0, 1, 0],
    [0, 1, 1, 0, 0],
    [0, 0, 0, 0, 1],
    [1, 0, 0, 1, 0],
    [1, 0, 0, 0, 0]
])

print(world)
print(f'The shape of the array is: {world.shape}')
print(f"The height of the world is: {world.shape[0]}")
print(f"The width of the matrix is: {world.shape[1]}")

[[0 0 0 1 0]
 [0 0 0 1 0]
 [0 1 1 0 0]
 [0 0 0 0 1]
 [1 0 0 1 0]
 [1 0 0 0 0]]
The shape of the array is: (6, 5)
The height of the world is: 6
The width of the matrix is: 5


In [15]:
# store indices of tree locations
indices = []
for y in range(len(world)):
    for x in range(len(world[y])):
        if world[y,x] == 1:
            indices.append((y,x))
print(indices)

[(0, 3), (1, 3), (2, 1), (2, 2), (3, 4), (4, 0), (4, 3), (5, 0)]


In [17]:
# store indices of tree locations
indices = [(y,x) for y in range(world.shape[0]) 
                 for x in range(world.shape[1]) if world[y,x] == 1]  

print(indices)

[(0, 3), (1, 3), (2, 1), (2, 2), (3, 4), (4, 0), (4, 3), (5, 0)]


In [18]:
# Define a function to plant a tree
def plant_tree(y, x):
    if y < world.shape[0] and x < world.shape[1]:
        world[y,x] = 1
        print(f'\n {world}')
        
plant_tree(0,2)


 [[0 0 1 1 0]
 [0 0 0 1 0]
 [0 1 1 0 0]
 [0 0 0 0 1]
 [1 0 0 1 0]
 [1 0 0 0 0]]


# Robot world

- A robot is navigating a 4x5 orange and blue world
- The robot has a sensor that tells it the color of the square its on top of 
and the color of the square directly to its right

<img src="world.png">

In [25]:
import numpy as np
world = np.array([
    ['o', 'b', 'o', 'o', 'b'],
    ['o', 'o', 'b', 'o', 'o'],
    ['b', 'o', 'o', 'b', 'o'],
    ['b', 'o', 'o', 'o', 'o']
    ])

measurement = ['b', 'o']

def find_match(world, measurement):
    possible_locations = [[y, x] for y in range(world.shape[0]) 
                                 for x in range(world.shape[1]-1) 
                                       if world[y,x] == measurement[0] and world[y,x+1] == measurement[1]]
    return possible_locations

locations = find_match(world, measurement)
print(locations)

[[0, 1], [1, 2], [2, 0], [2, 3], [3, 0]]


In [35]:
print(world)
world_1d = np.reshape(world, (1, -1))
print(f'\n {world_1d}')

[['o' 'b' 'o' 'o' 'b']
 ['o' 'o' 'b' 'o' 'o']
 ['b' 'o' 'o' 'b' 'o']
 ['b' 'o' 'o' 'o' 'o']]

 [['o' 'b' 'o' 'o' 'b' 'o' 'o' 'b' 'o' 'o' 'b' 'o' 'o' 'b' 'o' 'b' 'o' 'o'
  'o' 'o']]


In [36]:
zero_world = np.zeros((5, 4))
print(zero_world)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
